general:
  site-name: 
  form-email: 
  logo_path: 
  logo-max-width: 
  logo-text: 
seo:
  site_name:
  title:
  type: website
  description:
  keywords:
  social_image:
social:
  instagram_username: 
  facebook_username:
  pinterest_username:
  linkedin_username: 
  twitter_username:
  tiktok_username:
  youtube_username:
brand:
  # Put colors in ''
  main_color: '#E4D7D3'
  feature_color: '#A1A67F'
  light_color: '#F6F1F0'
  dark_color: '404232'
  primary_logo_path: 
  secondary_logo_path:
  submark_logo_path:
technical:
  google-analytics_tag:
  instagram_widget_embed: