general:
  site-name: 
  email: connect@embodiedayurvedaretreats.com
  logo_path: 
  logo-max-width: 
  logo-text: 
retreats: 
  ayurvedic-internship: 
    title: Ayurvedic Internship in Bali
    description: Hands on clinical training for students and practitioners of Ayurveda
    upcoming-date: October 17 - 27, 2025
    location: Ubud, Bali
    featured-image: /images/embodied-ayurveda-4.jpeg
seo:
  site_name: Embodied Ayurveda
  title: Embodied Ayurveda
  type: website
  description: 
  keywords: Ayurvedic Internship, Ayurvedic Internship in Bali, Dr. Resmi
  social_image:
social:
  instagram_username: 
  facebook_username:
  pinterest_username:
  linkedin_username: 
  twitter_username:
  tiktok_username:
  youtube_username:
brand:
  primary_logo_path: 
  secondary_logo_path:
  submark_logo_path:
technical:
  google-analytics_tag:
  instagram_widget_embed: