general:
  site-name: 
  email: connect@embodiedayurveda.co
  logo_path: 
  logo-max-width: 
  logo-text: 
retreats: 
  ayurvedic-internship: 
    title: Ayurveda in Practice
    description: Clinical Training Retreat
    upcoming-date: April 8 - 18, 2026
    location: Ubud, Bali
    featured-image: /images/embodied-ayurveda-4.jpeg
  yoga: 
    title: Ayurvedic Applications of yoga
    description: Where Ayurveda meets the mat
    upcoming-date: October 2025
    location: Koh Phangan, Thailand
    featured-image: /images/embodied-ayurveda-4.jpeg
seo:
  site_name: Embodied Ayurveda
  title: Embodied Ayurveda
  type: website
  description: Bridging the gap between theory and practice through hands-on trainings in inspiring locations.
  keywords: Ayurvedic Internship, Ayurvedic Internship in Bali, Dr. Resmi, Ayurveda yoga therapy, Ayurvedic application of yoga, Dr. Scott Roos
  social_image:
social:
  instagram_username: 
  facebook_username:
  pinterest_username:
  linkedin_username: 
  twitter_username:
  tiktok_username:
  youtube_username:
brand:
  primary_logo_path: 
  secondary_logo_path:
  submark_logo_path:
technical:
  google-analytics_tag: G-J9M57HVQQ6
  instagram_widget_embed: